// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence.Db;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230302164555_SeedDataAdditition")]
    partial class SeedDataAdditition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f892b173-da9a-43d4-8653-d4cf2556651d"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2023, 1, 2, 16, 45, 55, 854, DateTimeKind.Utc).AddTicks(4747),
                            Description = "Activity 2 months ago",
                            Title = "Past Activity 1",
                            Venue = "Pub"
                        },
                        new
                        {
                            Id = new Guid("6de34304-6ab7-49c9-84bb-4ba8a0fa9f05"),
                            Category = "culture",
                            City = "Paris",
                            Date = new DateTime(2023, 2, 2, 16, 45, 55, 854, DateTimeKind.Utc).AddTicks(4758),
                            Description = "Activity 1 month ago",
                            Title = "Past Activity 2",
                            Venue = "Louvre"
                        },
                        new
                        {
                            Id = new Guid("c67701c2-92e8-45ca-ab04-538c5f95a711"),
                            Category = "culture",
                            City = "London",
                            Date = new DateTime(2023, 4, 2, 16, 45, 55, 854, DateTimeKind.Utc).AddTicks(4763),
                            Description = "Activity 1 month in future",
                            Title = "Future Activity 1",
                            Venue = "Natural History Museum"
                        },
                        new
                        {
                            Id = new Guid("f03a6fc7-ecf7-4332-8c07-bb9949fde259"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2023, 5, 2, 16, 45, 55, 854, DateTimeKind.Utc).AddTicks(4767),
                            Description = "Activity 2 months in future",
                            Title = "Future Activity 2",
                            Venue = "O2 Arena"
                        },
                        new
                        {
                            Id = new Guid("cdc4a30d-1e68-4a82-b896-0fc775485496"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2023, 6, 2, 16, 45, 55, 854, DateTimeKind.Utc).AddTicks(4770),
                            Description = "Activity 3 months in future",
                            Title = "Future Activity 3",
                            Venue = "Another pub"
                        },
                        new
                        {
                            Id = new Guid("c531332b-392f-4ff5-96e7-515732985617"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2023, 7, 2, 16, 45, 55, 854, DateTimeKind.Utc).AddTicks(4772),
                            Description = "Activity 4 months in future",
                            Title = "Future Activity 4",
                            Venue = "Yet another pub"
                        },
                        new
                        {
                            Id = new Guid("394143f9-9b69-4f5b-8fb5-b552b1d41dc3"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2023, 8, 2, 16, 45, 55, 854, DateTimeKind.Utc).AddTicks(4775),
                            Description = "Activity 5 months in future",
                            Title = "Future Activity 5",
                            Venue = "Just another pub"
                        },
                        new
                        {
                            Id = new Guid("be4cefd3-eb84-4624-909f-a011eec20e2c"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2023, 9, 2, 16, 45, 55, 854, DateTimeKind.Utc).AddTicks(4788),
                            Description = "Activity 6 months in future",
                            Title = "Future Activity 6",
                            Venue = "Roundhouse Camden"
                        },
                        new
                        {
                            Id = new Guid("00966db1-31e3-4003-affc-c27257a3e1d0"),
                            Category = "travel",
                            City = "London",
                            Date = new DateTime(2023, 10, 2, 16, 45, 55, 854, DateTimeKind.Utc).AddTicks(4791),
                            Description = "Activity 2 months ago",
                            Title = "Future Activity 7",
                            Venue = "Somewhere on the Thames"
                        },
                        new
                        {
                            Id = new Guid("cbf4fe24-86e5-46e8-914a-494450da5a55"),
                            Category = "film",
                            City = "London",
                            Date = new DateTime(2023, 11, 2, 16, 45, 55, 854, DateTimeKind.Utc).AddTicks(4794),
                            Description = "Activity 8 months in future",
                            Title = "Future Activity 8",
                            Venue = "Cinema"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
